### ISSUE TITLE
Add-on Screws Up Dialog Box Options

### ISSUE THREAD

**Issue by EricBartha** [isaacdew/webtimeclock#1]
Upon installation, the add-on effectively removes the option to "Don't Save" when closing an unsaved document. It centers "Save" and "Cancel" but removes the "Don't Save" button entirely. Other dialog boxes were not checked.

**Comment by isaacdew** [comment]
Thank you for notifying me of this issue. Please update to version 1.0.1 in which this error has been resolved.
